### ISSUE TITLE
hard timeouts are being reached

### ISSUE THREAD

**Issue by retronym** [lightbend/dbuild#102]
``` scala
object Timeouts {
  // overall timeout for the entire dbuild to complete;
  // should never be reached, unless something truly
  // unexpected occurs. One of the subsequent other
  // timeouts would rather be encountered beforehand.
  val dbuildTimeout: Timeout = 5.hours + 30.minutes
```

Maybe the "truly unexpected" thing was us getting all of these projects to work in one build?

https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-retronym/buildTimeTrend

In any case, we're hitting the limit now, and need to make it configurable.

I also would love to see per-project timings in the summary so we could know where the time is being spent without piecing that together from the log file. Would also be useful to know the breakdown between compilation, doc generation, and test execution.

/cc @adriaanm @gkossakowski

**Comment by cunei** [comment]
The hard timeouts are fixed in recent commits: beginning with version 0.9.10 all the timeouts can be freely configured (and are properly captured)
