### ISSUE TITLE
The quick example in the docs no longer works

### ISSUE THREAD

**Issue by dwijnand** [lightbend/dbuild#186]
I'm learning dbuild, and I've found that the quick example in http://typesafehub.github.io/dbuild/0.9.5/introduction.html#a-quick-example no longer works.
1. jsuereth/sperformance doesn't provide an sbt version. I fixed that with `extra.sbt-version: 0.13.12`
2. the scala project doesn't build, because there's no `dbuild-meta.json` in the 2.10 branch

There might be more, but I gave up at that point.

**Comment by dwijnand** [comment]
See https://github.com/scala/scala/pull/2704/commits/a0a60e709fa8041a482f2389104b8c17443c5526 for when `dbuild-meta.json` was added to scala when master was building towards 2.11.0.

**Comment by cunei** [comment]
Fixed in 0.9.10

**Comment by dwijnand** [comment]
excellent, thanks Toni
