### ISSUE TITLE
support shallow cloning of repositories?

### ISSUE THREAD

**Issue by SethTisue** [lightbend/dbuild#209]
`git clone --depth=1` can save a lot of time (and bandwidth and disk space) if you don't need the history. could dbuild support this as an option...?

for example, the akka/akka repository clones about 10x faster this way

**Comment by cunei** [comment]
Hi @SethTisue, in principle dbuild does not need to re-clone the remote repository each time: there is a single local clone that is just updated at every run. The other clones take place on the local file systems, and are mode very efficiently using hard links. Unless you deliberately delete the master clone (which is in a subdirectory of the `clones-0.9.12` directory), each run should have no need to clone the remote from scratch. A more detailed description is available here: https://github.com/lightbend/dbuild/issues/171#issuecomment-119769616

**Comment by SethTisue** [comment]
I guess I encountered an unusual set of circumstances:

* I had just upgraded to dbuild 0.9.12 so everything needed to be re-fetched
* I was on a slow connection

but yeah, now that I think about it some more, this probably isn't worth doing.
